### ISSUE TITLE
[FEATURE] - option not to show in Notifications

### ISSUE THREAD

**Issue by timur-g** [zaneschepke/wgtunnel#106]
When a tunnel is enabled, in Android notifications I see "VPN connected. Connected to tunnel Name".
It may be useful but I would like to have an option not to show this in Notifications.
For 2 reasons: it takes space and I know when tunnel works because I use mails over it.
Thanks.

**Comment by zaneschepke** [comment]
Hello! Unfortunately, because the app is using foreground services to allow the VPN to persist after the app has been closed, the persistent notification is required. However, in Android 14 these persistent notifications can be dismissed so they do not take up space in your notification tray. 

If you have any more questions on this topic, feel free to reach out. I will mark this one as closed for now.
