### ISSUE TITLE
[BUG] - 3.3.9 cuts connection name

### ISSUE THREAD

**Issue by kslcsdalsadg** [zaneschepke/wgtunnel#143]
**Describe the bug**
The connection name is cut

**Smartphone (please complete the following information):**

- Device: Google Pixel 7 Pro
- Android Version:  Android 14
- App Version 3.3.9

**To Reproduce**
Create a connection with a medium large name. e.g. "roberto@xxxxxxxxxxx"
Go to the connections list

**Expected behavior**
The connection name is displayed due to is not too large

**Screenshots (Only if necessary)**

![image](https://github.com/zaneschepke/wgtunnel/assets/31618496/2f146892-2abc-419b-8237-f53b6246dc91)

**Comment by zaneschepke** [comment]
Hello! I added this behavior because I do not currently limit name sizes like the official app does. To prevent impacting the UI and functionality, I shortened the display name if it is over a certain size. Right now if it is over 18 characters long I am removing all additional characters from the displayed name and changing the last three to ***. 

I can change this behavior if there is a more desirable solution.

**Comment by kslcsdalsadg** [comment]
Hello,
I have tried to find layout files at code but no luck...
In any case, why you can create a RelativeLayout foreach connection then fix the buttons at right/end then the text from left/start to leftto buttons then configure the TextField to automatically cutoff the text at middle or right?
Thanks in any case
