### ISSUE TITLE
Amazon firestick tv support 

### ISSUE THREAD

**Issue by matrix2673** [zaneschepke/wgtunnel#186]
hello , I recently discovered this excellent client, I tried to install it on Amazon's Firestick TV Android, I detected a problem when adding the configuration file, when I go to add via + button I can't navigate to the folders of the device, is it possible to check ? Or make the client compatible for Amazon if it isn't? Thanks in advance.

**Comment by matrix2673** [comment]
Original app doesn't have this problem goes directly to list all folders /storage/emulated/0

**Comment by zaneschepke** [comment]
Hello! The reason the original app works is because they built an entire file browser from scratch and that's why it works on FireTV. I am not willing to do this work for this app. I do not own a FireTV to test and FireTV does not support the standard file browser android API. 

For a full list of reasons why I stopped supporting FireTV and for a workaround to this getting WG Tunnel working on FireTV, see [here](https://zaneschepke.com/wgtunnel-docs/faq.html#firetv-faq).
