### ISSUE TITLE
FR: Merging Android Dynamic Shortcuts

### ISSUE THREAD

**Issue by mich2k** [zaneschepke/wgtunnel#21]
Some months ago I was following a discussion about the Android Dynamic Shortcuts integration into the official Wireguard android app

https://github.com/WireGuard/wireguard-android/pull/55
https://github.com/WireGuard/wireguard-android/pull/48

I think it would be a great feature since beyond the customization, these would also give for free the "trusted wifi" feature that even if works good to me (I am doing some futher testing on my phone about #15) some phones may just work better with the dyn shortcuts approach or some users would just prefer this or may have less battery impact.. in this way users would still get the extended features & support of this app compared to the official one

**Comment by zaneschepke** [comment]
Thank you for the info on this. Does this replace the need for Quicktiles? I am currently working on a feature for Quicktiles but there seems to be a lot of overlap in these two features.

**Comment by zilexa** [comment]
This is about app shortcuts. In Android an app can, besides the app itself, also present widgets and shortcuts to the system, which gets propagated to for example the launcher apps. 
The shortcuts be used on your homescreen or by long pressing the app icon on your homescreen.
Additionally, other apps can use the app shortcuts as well.
It's a bit of an old Android feature. For example, music recognition apps like Shazam and the former TrackID apps, allowed for a shortcut to be placed on the homescreen. The advantage was that if you click that, instead of the app icon, recognition started directly. 
Nowadays I think it's more commonly used when long pressing an app icon, a context menu is presented with the actions.

**Comment by mich2k** [comment]
> This is about app shortcuts. In Android an app can, besides the app itself, also present widgets and shortcuts to the system, which gets propagated to for example the launcher apps. 
> The shortcuts be used on your homescreen or by long pressing the app icon on your homescreen.
> Additionally, other apps can use the app shortcuts as well.
> It's a bit of an old Android feature. For example, music recognition apps like Shazam and the former TrackID apps, allowed for a shortcut to be placed on the homescreen. The advantage was that if you click that, instead of the app icon, recognition started directly. 
> Nowadays I think it's more commonly used when long pressing an app icon, a context menu is presented with the actions. 
> 

I think the most common use case would be Google routines, bixby etc integrations

**Comment by BaronAdam** [comment]
I still don't see this feature in the version released In Play Store what's the matter with that?
