### ISSUE TITLE
[BUG] - Loosing connectivity when roaming from private network to public network 

### ISSUE THREAD

**Issue by baltoche** [zaneschepke/wgtunnel#234]
**Describe the bug**
When I leave my wifi network (where the DNS points to a local ip) and my phone switches to mobile network (where the DNS points to a public ip) I lose connectivity but the VPN thinks it is still connected. 

**Smartphone (please complete the following information):**

- Device: fairphone 5
- Android Version: Android 13
- App Version 3.4.4

**To Reproduce**
Switch between 2 networks that don't use the same ip for the vpn

**Expected behavior**
If the VPN is configured with a domain name the ip should be updated when switching network (and not through the VPN obviously) 

PS: thank you to all contributors for this great software.

**Comment by kafisc1** [comment]
I can confirm the issue.

**Comment by zaneschepke** [comment]
Hello! This is something that the restart on ping failure feature should help fix. There is really no simple solution to fixing this issue without restarting the tunnel or tweaking your DNS setup. I know the ping restart feature is having issues right now, but I plan on spending some more time on it to make it more robust and configurable.

**Comment by bobpaul** [comment]
>If the VPN is configured with a domain name the ip should be updated when switching network (and not through the VPN obviously)

I've seen this in tools like [wireproxy](https://github.com/pufferffish/wireproxy) which has an option to specify a public IP address to use for resolving the tunnel host, but this is definitely not something that I would expect to happen by default. That's an additional feature. 

Generally in Wireguard, It's assumed that only of the peers changes their IP address at a time (your phone roams from a wifi address to a cellular address). In the situation you're describing, both peers changed endpoints at the same time (your phone got a new IP address and your VPN server also got a new address). That's the fault of how you have it configured.

----

If I understand the problem, you have some `vpn.example.com` which points to a computer on your LAN on your home network, but points to the WAN address of your router (which does port forwarding) when you're outside you're home, is that correct?

In that case, you should configure "[NAT Reflection](https://docs.opnsense.org/manual/how-tos/nat_reflection.html)" on your router. [TpLink calls this NAT Loopback](https://community.tp-link.com/en/home/stories/detail/1726). Other's call it "Reflexive NAT".

**Without NAT Reflection**
Without NAT reflection, ports that your forward from your router's WAN address to a computer on your network are only forwarded if the requests are received on the router's WAN port.

```mermaid
flowchart TD
    phone --DNS: vpn.example.com?--> onedotone[1.1.1.1]
    onedotone --DNS 111.222.333.444--> phone
    router <--lanport--> LAN
    subgraph LAN
      wg{{wireguard
       server}}
    end
    subgraph internet
        phone
        onedotone
    end
    phone[phone] --wg: 111.222.333.444:51280--> router
    router --wg: 192.168.0.10:51820-->wg
```

```mermaid
flowchart TD
    internet <--wanport-->
    router
    phone --DNS: vpn.example.com?--> router
    router --DNS: 192.168.0.10--> phone
    subgraph LAN
      wg{{wireguard
       server}}
      phone
    end
    subgraph internet
    end
    phone --wg: 192.168.0.10:51820-->wg
    phone --wg: 111.222.333.444:51820--x router
```

**With NAT Reflection**
With NAT reflection, ports that your forward from your router's WAN address to a computer on your network are forwarded to your computer even if the requests come on the LAN port.

```mermaid
 flowchart TD
    internet <--wan-->
    router
    phone --DNS: vpn.example.com?--> router
    router --DNS: 111.222.333.444--> phone
    subgraph LAN
      wg{{wireguard
       server}}
      phone
    end
    subgraph internet
    end
    phone --wg: 111.222.333.444:51820-->router
    router --wg: 192.168.0.10:51820-->wg
```

If you enable NAT reflection, you can always use the WAN address of your router, even from inside your network. You can set DNS that always points to that address.

**Comment by zaneschepke** [comment]
Thank you @bobpaul for this excellent explanation. I think NAT reflection would be the ideal solution. You could also use the less ideal solution and use the restart on ping failure feature which would bounce the tunnel and reconnect on the public wifi which would then connect to your WAN port.

**Comment by nktnet1** [comment]
Thanks for the diagram @bobpaul - that was really helpful!

---

I have a similar issue where my ISP router doesn't support NAT Loopback (aka NAT Reflection / Hairpin Nat / Hairpinning).

When I'm outside the network (e.g. cellular/mobile data) connecting to my wireguard instance via a public domain, everything is fine. However, when I'm inside the network (e.g. home Wi-Fi), the connection fails.

My router does support port forwarding, so I'm able to use Adguard Home as my DNS server, allowing me to rewrite my public domain to the local IP address where wireguard is running while using Wi-Fi.

When the [Dynamic DNS auto-update](https://wgtunnel.com/docs/tunnels#dynamic-dns-updates) option is enabled, switching from the home Wi-Fi to cellular correctly changes the endpoint from my local IP to public IP.

However, switching from cellular back to the home Wi-Fi network does **not** update the endpoint back to the local IP, thus requiring a manual toggle off then back on.

@zaneschepke Do you know why this is the case? I also tried looking for the

> restart on ping failure feature

you mentioned, but couldn't find it in the app or documentation. I do see the code for it here:

https://github.com/wgtunnel/wgtunnel/blob/bdd7c9689c6c5fea61ab110e1225421d434acfcc/app/src/main/java/com/zaneschepke/wireguardautotunnel/ui/screens/tunnels/settings/TunnelSettingsScreen.kt#L136-L139

which means it should be somewhere in tunnel settings:

<img width="300" alt="tunnel-settings" src="https://github.com/user-attachments/assets/cce1c4b6-9c79-41a7-a2bf-f53f53be30ee" />

&nbsp;

Is there anything I need to toggle to see this option? Or has it just been renamed to Dynamic DNS auto-update?

I'm using version 4.2.2 installed from F-Droid.

---

**UPDATE:**

I think the Adguard rewrite doesn't work is because when switching from cellular to the home Wi-Fi, DNS stops working so the Endpoint can't update to the local IP at all.

Whereas, if we manually turn off the wireguard connection, then turn it back on, DNS will work in the time that wireguard is off and hence can perform the IP update.

Is there any way around this? :(
