### ISSUE TITLE
[BUG] - (maybe) Autotunnel starts when connected to trusted WiFi

### ISSUE THREAD

**Issue by Jasperatus** [zaneschepke/wgtunnel#254]
**Describe the bug**
Appologies because I'm afraid it's default en expected behaviour for android (unfortunately) and yet I still make an issue, sorry:
When WiFi is off and I turn it on, it connects to my trusted WiFi, and the app enables the tunnel. 
This is when my GPS is turned off, which is all of the time. I only enable it when I need to use it... If my GPS is turned on, it appears to not enable the vpn. 

**Smartphone (please complete the following information):**

- Device: Samsung Galaxy S23
- Android Version: Android 14
- App Version: 3.4.6

**To Reproduce**

Turn off WiFi and GPS. Then turn on WiFi and phone connects to trusted WiFi. 

**Expected behavior**
That the tunnel doesn't enable when on trusted WiFi when GPS is off. 

**Screenshots (Only if necessary)**

**Additional context**
I'm afraid this is normal and expected behaviour by/because of android... But I hope(d) that there is a way around.

**Comment by zaneschepke** [comment]
Hello! No worries. Yes, this is unfortunately an android limitation because wifi name is considered location data.  

I think the best way around this (from a privacy perspective) is to use an alternative android flavor that helps you retain some level of privacy while still being able to use location services. I highly recommend GrapheneOS for this and for many other reasons. 

You can read more about how they accomplish this here: https://grapheneos.org/faq
