### ISSUE TITLE
F-Droid or releases APK

### ISSUE THREAD

**Issue by K4sum1** [zaneschepke/wgtunnel#26]
Not everyone likes or wants to use the Google Play Store, so having an official APK in a third party store or under releases would be nice.

**Comment by zaneschepke** [comment]
In order to make this happen, it looks like I am going to have to switch database libraries. I'm currently using ObjectBox which is supposed to be FLOSS but certain hidden aspects of it are not. F-Droid has flagged this and denied my app. They also took down many other apps from their store over this issue. It seems like a lot of people have been blindsided by this. I just wanted to give an update that deploying will take a bit more time because of this change. 

https://github.com/objectbox/objectbox-java/issues/1102
https://github.com/objectbox/objectbox-java/issues/1100
https://github.com/objectbox/objectbox-java/issues/560

**Comment by K4sum1** [comment]
I'm curious why is specifically ObjectBox blocked and not just an anti-feature?

**Comment by zaneschepke** [comment]
> I'm curious why is specifically ObjectBox blocked and not just an anti-feature?

I'm not entirely sure but I believe it is because it is closed source. I think anti-features are more for non-free features but I could be wrong. 

Either way, the latest release [2.5.0](https://github.com/zaneschepke/wgtunnel/releases/tag/2.5.0) I have migrated the app to Room for db, Zxing for QR codes, and created a new flavor specifically for F-Droid which removes all Google Crashlytics/Analytics. I actually prefer this as now there can be a fully FLOSS version of the app. 

We are in the final stages of resolving some pipeline issues for deploying to F-Droid. I'll keep you posted on the progress!

**Comment by zaneschepke** [comment]
Update: The pipeline was completed successfully about one week ago. We are now waiting on F-Droid to complete the app signing. Once that is completed, I assume they will add it to the store. They were unable to provide a timeline. Unfortunately, this is a very long and slow process.

**Comment by zaneschepke** [comment]
We are officially on F-Droid! Special note, although F-Droid and Google Play versions are similar, the main difference is the F-Droid version has no Google Analytics/Crashlytics while the Google Play version does.
