### ISSUE TITLE
[FEATURE] - activate wg tunnel for specific applications connecting own servers

### ISSUE THREAD

**Issue by togme** [zaneschepke/wgtunnel#262]
**Is your feature request related to a problem? Please describe.**
yes, I have juice and it works only with the dns resolution of my home server and all of the (local) vms and docker instances.

**Describe the solution you'd like**
If I start juice and I am outside of my own wifi networks, wg tunnel should start the associated tunnel. In this case to my fritzbox or my proxy vm on the host.

**Describe alternatives you've considered**
I have to start the tunnel for this application manually and it is active for all other apps too.
 
**Additional context**
I don't know anything more :-)

**Comment by jsnfwlr** [comment]
You can configure tunnels to include or exclude apps, so if 6ou only want JuiceSSH to use a tunnel in certain circumstances, duplicate the tunnel config and set the app settings to Include just JuiceSSH.

As for auto-connecting the tunnel when you open JuiceSSH, that would require the App-Usage permission be added to WG-Tunnels, along with a lot more config UI and logic around when to apply tunnels.

What happens if I have a tunnel set to auto-start tunnel when I am mobile data and one to auto-start when I open JuiceSSH, and then I open JuiceSSH while I am on mobile data?

**Comment by zaneschepke** [comment]
Hello! I think this issue is already solvable with split tunneling + auto tunneling as @jsnfwlr described. Thanks for the detailed explanation! 

If you have any additional questions on how to set this up, please check out the docs or feel free to reach out again here or on one of our chat rooms. Thanks!
