### ISSUE TITLE
[FEATURE] - Disabling auto-tunneling qucktile should deactivate vpn

### ISSUE THREAD

**Issue by ElbPirat** [zaneschepke/wgtunnel#291]
**The Problem**
I am using my wireguard vpn all the time, since I use a dsn adblock at home.
But sometimes I need to have the vpn deactivated for special services (Car Sharing App, connecting to Spotify connect device, trying website without adblock,...).
Now I have either the option to use (1)"activate tunnel"-QT or (2)"activate auto tunnel"-QT.

(1) will not work if auto-tunnel rules are in conflict => for me all the time, as I am not in my "known network" => triggers VPN on instantly again
(2) will only disable the auto-tunnel, I still need to deactivate the tunnel manually by opening the manager app

**My Suggestion**
Instead of only disabling the auto-tunnel feature, using (2) should also disable the VPN connection (optional: only if enabled by auto-tunnel).
This way the user can disbale auto-tunnel and vpn with one click on the QT. I think this is most of the time the case anyway.
Enabling (2) again, will check if vpn needs to be connected and activates it accordingly (existing behavior).

I don't see a reason why someone would only deactivate the auto-tunnel, but not the VPN, from outside the manager-app.

**Alternatives**
I am not quite sure if this is possible.
But adding long-press actions to the QT could also be a option, but this inceases the complexity of the QT.
Short press => Disable only auto-tunnel
Long press => Disable auto-tunnel + vpn

Also another quick setting tile could be added. Using the same method as the previous one + disabling the vpn.

Or like a "Pause WG Tunnel"-QT, maybe even by adding a timer. Default duration in settings, long press = infinity.

**Comment by zaneschepke** [comment]
Hello! Option 1 should be working now as the app allows for manual override of auto tunneling if you toggle a tunnel manually while auto tunneling is enabled. Auto tunneling will take back over on the next network change instead of toggling the tunnel back on instantly. As far as stopping the tunnel when auto tunnel is stopped, I think this makes sense, but I'll have to think about that more. Considering option 1 is now functioning, I think we can mark this one as closed. We can reopen if you would really like to see option 2 add as well.
