### ISSUE TITLE
[FEATURE] - New feature request: Always-on VPN﻿ + Restart on ping fail

### ISSUE THREAD

**Issue by dsh2dsh** [zaneschepke/wgtunnel#321]
Hi,

**Describe the solution you'd like**
Is it possible to combine somehow "Always-on VPN" option and "Restart on ping fail" option? My goal is to always use WG, but I'm OK to use a public network if my WG server is not accessible for some time.

Thanks.

**Comment by Tinsus** [comment]
Hi there, i would like to upvote this request - otherwise I would have the same suggestion but based on another problem:

Kinda randomly my WG-host gets a new IP, when that happens my phone is connected using WiFi/network and always on-VPN, but has no functional traffic without any identication of that. In this case I have to turn off the tunnel and reenable it.

So it would be great not only to show a yellow indicator in the app if the pings goes bad but also to soft-reset the connection (maybe up to x times every z seconds) and if that fails to show a notification.
This would prevent my to be annoied about this app because the connection is broken without some 'larger' technical probkems in its setup nor the servers

**Comment by zaneschepke** [comment]
This is now added to the latest nightly version. You can now enable restart on ping and activate it by turning on auto tunnel. This is allowed while having AOVPN enabled. Let me know if you have any issues with it and we can reopen.

**Comment by dsh2dsh** [comment]
Thanks.

I installed the nightly and I'm testing AOVPN together with `Restart on ping fail (beta)`. Global settings shows me `Restart on ping fail (beta)`  is on and below I see `Stop auto-tunneling`. So I suppose pings are enabled.

In tunnel configuration I `Set custom ping ip` to `192.168.222.1`. This is IP of my server inside WG tunnel. BTW, I can't remove this IP from this field. It doesn't allow me make it empty.

Anyway, on the server I launched `tcpdump -i wg0 host 192.168.222.1` and I'm expecting to see pings every 60 seconds. But I don't see it. So I'm not sure this feature works at all.

The tcpdump works fine, I tested it by removing `host 192.168.222.1` and I see lots of traffic.
