### ISSUE TITLE
[BUG] - most of the time status icon ia yellow instead of green

### ISSUE THREAD

**Issue by kslcsdalsadg** [zaneschepke/wgtunnel#323]
When I enter the app the connection status icon at left of the connection name is yellow instead of green

- Device: Pixel 7 Pro
- Android Version: 14, GrapheneOS
- App Version: 3.5.

[Uploading wg_tunnel_logs-1724260079.txt…]()

**Comment by zaneschepke** [comment]
Hello! I also use grapheneOS and basically what the yellow is signifying is that there has not been a tunnel handshake in a while. If you click on the tunnel you can view the statistics and see the last handshake time. This is expected behavior if there is no traffic going through the tunnel. When you start performing network related tasks, it goes green again. 

I am definitely open for to ideas on how to better display this information, but I'll mark this bug as closed for now. 

Feel free to add any further feedback here or open a new feature ticket with ideas on how to improve this behavior.
