### ISSUE TITLE
AndroidTV issue when trying to import tunnel from file

### ISSUE THREAD

**Issue by tonyhardcode** [zaneschepke/wgtunnel#35]
I get the error "You don't have an app that can do this" when trying to import a tunnel from files. I have the FX file manager installed and it works when importing files into other apps (just checked with the OpenVPN app before putting in this ticket). I was using this method before but I think it might have broke with a recent WG Tunnel update.

**Comment by zaneschepke** [comment]
Thank you for reporting this. I have a few other people saying they are experiencing the same thing. I use Cx File Explorer on my Chromecast, and it works well. I changed the original implementation because I was getting reports it was not working on FireTVs. I'll take a look at how OpenVPN opens files.
