### ISSUE TITLE
[BUG] - Trusted WiFi problem

### ISSUE THREAD

**Issue by R7010A** [zaneschepke/wgtunnel#368]
**Describe the bug**
Hello I have a problem that I can't get solved. I have added trusted Wi-Fi networks, but it is no longer recognized as trusted. I don't know if it was already like that before v.3.5.2. I discovered this while downloading a file (4.6 MB) from the net. When I'm at home (this Wi-Fi network is defined as trustworthy), the download takes a long time because of the VPN connection. Only when I manually deactivate WG is the download done in 1 second. This showed me that the "Trusted Wi-Fi" function probably doesn't work for me. Does anyone have an idea?

**Smartphone (please complete the following information):**

- Device: OnePlus Nord 3 5G
- Android Version: Android 14
- App Version: 3.5.2

**Comment by zaneschepke** [comment]
Hello! It sounds like you are using kernel mode. I recommend adding the app tunnel quick tile to your quick tile settings to better help you see the state of the tunnel. 

Since adding wifi trusted wildcards, there are a few issue with special characters in wifi names as described in issue #363. Perhaps one of these issues is causing you problems. I'm working on a fix. 

Another common issue with trusted Wi-Fi is if you have turned off "Allow all the time location" permission or you have turned off location services on your phone. Both are currently required for this feature to work properly. There is a request (when using kernel mode) to be able to grab the current wifi name using the shell so rooted android devices do not require these permissions. When I get some time, this would be a really nice feature I'm looking to implement. #322 

I recommend looking at the in app logs feature when you switch networks. It will tell you if it is detecting a valid SSID when you switch network or if it is lacking permissions and getting an invalid SSID back from the system.

**Comment by R7010A** [comment]
Hello Zane, I can't use kernel mode because my phone is not rooted. Both Tiles of WG-Tunnel are in the Quick Settings, but the Auto-Tunnel Tile is always grayed out and the Tunnel Control Tile is always on, whether I'm on a trusted Wi-Fi or not. Permanent localization is activated, as is the location service. If I watch the log while turning Wi-Fi on and off, it doesn't give me an SSID at all. I've attached a log to you. Maybe you'll take a look. Thank you.

[Uploading wg_tunnel_logs-1727539203.txt…]()

**Comment by zaneschepke** [comment]
No worries! Perhaps I can do more to make that button more obvious. I'll think on that one. I'm glad things are working well for you now!
