### ISSUE TITLE
FireTV unable to import configuration file

### ISSUE THREAD

**Issue by yo12222** [zaneschepke/wgtunnel#39]
Issue #34.
Reopening as this is still not fixed on v3.0.3 (verified in app).
Trying to import a tunnel sends me to a screen that shows "Recent" (as recently opened files) with nothing in it.
However, if you press the select button right after reaching that default file browser screen, you can open the left menu.
The left menu contains nothing, unless you install a file browser like cxfilebrowser and then you can see other stuffs like downloads, processes, etc..
Yet, nothing is selectable.

In general, the moment you reach that default import file screen, you have 1 button press to do, after that, you cannot do anything at all.
Its like the arrows buttons do nothing and you are currently not hovering any button, youre stuck, with nothing else to do.

FireTv Stick 4K Max from friend.
He has the last edition.

**Comment by zaneschepke** [comment]
Thank you for reporting this. I have been hearing similar reports from other FireTV users. I am unable to test more intensively because I do not have a FireTV. The user I have been testing with tells me the app works fine if you install it sideload and not from the FireTV store. Is this the case for you as well?

**Comment by yo12222** [comment]
I see only source code in the release.
Do you have a trusted apk from you i could try to sideload with or i need to build it from source myself?
Thanks.

**Comment by zaneschepke** [comment]
Yes, if it is possible to install F-Droid on FireTV I would recommend that otherwise F-Droid website is the best place to get the official APK for this app. https://f-droid.org/en/packages/com.zaneschepke.wireguardautotunnel/. Please install the latest version.

**Comment by yo12222** [comment]
I downloaded the source code and built it and "adb install"'ed it.
Same exact thing, it opened the default file browser and am stuck.

**Comment by yo12222** [comment]
The normal wireguard opens a different file browser and it works there.
Maybe you could check how they do this in their source code?

**Comment by zaneschepke** [comment]
> The normal wireguard opens a different file browser and it works there. Maybe you could check how they do this in their source code?

Okay, I will have to investigate further. Yes, I will check how WireGuard official app is handling this. I am also currently working on a way to add configs manually (although I realize that is still not an ideal solution). I will keep you posted on the progress.

**Comment by zaneschepke** [comment]
Are you willing to let me pass you an APK to try? Also, if you have Discord to chat or send me an email then we can communicate a bit faster :)

**Comment by zaneschepke** [comment]
I'm reopening as this is still not fixed :( I think I finally have a solution but I have no way to test. @yo12222 Would you be willing to test this fix for me if I pass you an apk file?

**Comment by abissoli** [comment]
Reopening as I have the same issue here using version 3.3.2 from F-Droid. May I help somehow to fix this?

**Comment by zaneschepke** [comment]
Hello, yes I will re-open this issue. From further research on this, it seems that some FireTV models just won't work with Android's standard way for selecting files from devices. The only way I can think to get this working is to write a completely custom file picker from scratch.  ☹️

**Comment by zaneschepke** [comment]
An update on this.. someone was able to get around this issue on their FireTV by using the following app [Android TV ADB Maus](https://play.google.com/store/apps/details?id=svarzee.android.apps.adb_mouse&amp;hl=en_US&amp;gl=US). With this app, you can navigate on the default FireTV file picker to select the desired folder and files.

**Comment by abissoli** [comment]
Thank you. In the meantime, I found another trick using a wireless
keyboard. I had to hit "search" on the keyboard, exit from the search
window and then I was able to browse the Download folder.
No way with the Amazon remote.



Il sab 20 gen 2024, 03:35 Zane Schepke ***@***.***> ha
scritto:

**Comment by zaneschepke** [comment]
It has been a long road trying to get FireTV working properly, but I have since decided that the best path forward is to drop official support for it for a few reasons:

1. They simply don't work with Android's file selector API. 
2. They have no way to emulate their devices to test
3. They have horrible developer support, terrible developer portal, and zero CI

These devices are just too hard to support and hardly seem to be supported by the very company that made them! 😆 

 That being said, they can still side-load the app and it will likely work (with a few of the workarounds listed here and in the docs). I think that is the best I can do for the FireTV, unless something major changes with their platform in the future. 

I have updated the docs to reflect this: https://zaneschepke.com/wgtunnel-docs/faq.html#firetv-faq

**Comment by tlambertz** [comment]
Just had the same issue. Sideloaded wgtunnel via the fdroid apk from GitHub releases, then used scrcpy to operate the file dialog.

Here my steps:

On FireTV with remote:

1. enable developer settings
2. enable ADB on FireTV
3. get IP from FireTV Info
4. copy wgtunnel apk + wg config file to firetv (via eg https://www.amazon.de/Datei-Manager-f%C3%BCr-Fire-Datei-Explorer-USB-OTG-Cloud-Netzwerk-WLAN-Freigabe/dp/B005FCD4M4 HTTP upload share)
5. install wgtunnel

On Computer:

6. connect to FireTV via ADB (`adb connect FIRETVIP:5555`)
7. connect to firetv with scrcpy (https://github.com/Genymobile/scrcpy): `scrcpy --video-codec=h265 -m720 --max-fps=60 --no-audio -K`
8. use mouse and keyboard on PC to select config file

scrcpy is a really excellent solution for remotely operating android devices, way better than any 'ADB Maus' app IMO.

**Comment by zaneschepke** [comment]
> Just had the same issue. Sideloaded wgtunnel via the fdroid apk from GitHub releases, then used scrcpy to operate the file dialog.
> 
> Here my steps:
> 
> On FireTV with remote:
> 
> 1. enable developer settings
> 2. enable ADB on FireTV
> 3. get IP from FireTV Info
> 4. copy wgtunnel apk + wg config file to firetv (via eg https://www.amazon.de/Datei-Manager-f%C3%BCr-Fire-Datei-Explorer-USB-OTG-Cloud-Netzwerk-WLAN-Freigabe/dp/B005FCD4M4 HTTP upload share)
> 5. install wgtunnel
> 
> On Computer:
> 
> 6. connect to FireTV via ADB (`adb connect FIRETVIP:5555`)
> 7. connect to firetv with scrcpy (https://github.com/Genymobile/scrcpy): `scrcpy --video-codec=h265 -m720 --max-fps=60 --no-audio -K`
> 8. use mouse and keyboard on PC to select config file
> 
> scrcpy is a really excellent solution for remotely operating android devices, way better than any 'ADB Maus' app IMO.

Sorry, are you saying this worked for you or you also had issues with these steps?

**Comment by tlambertz** [comment]
Heh, sorry for being unclear. My steps worked great! Just wanted to post here if in case anyone needs a more detailed guide how to do it.

(The UI of wg-tunnel is still really janky, hard to select correct buttons with the remote, text-field popping up. But i mostly need it to do the automated turn-on of VPN, and selection of apps to do split-tunneling, both are a bit janky with the 'default' wireguard android app. Rarely interact with the UI, so that's not much of an issue for me).
