### ISSUE TITLE
[BUG] - Auto Tunnel activates on blacklisted WiFi networks

### ISSUE THREAD

**Issue by technikamateur** [zaneschepke/wgtunnel#416]
**Describe the bug**
I have setup all networks, where wgtunnel should not auto activate.
However this does not work for my wifi called `---Wire--- ( Less )))`

**Smartphone (please complete the following information):**

- Device: Pixel 8a
- Android Version: Android 14
- App Version latest
- Backend: Stock Android not rooted.

**To Reproduce**

1. Have a wifi network with the name `---Wire--- ( Less )))`
2. Blacklist it
3. Activate Auto Tunnel 

**Expected behavior**
Tunnel should not activate on blacklisted networks.

**Screenshots (Only if necessary)**

**Additional context**

**Comment by tomcat-xx** [comment]
For me this was solved now by stopping and re-starting auto runneling in settings screen (NOT pause and resume on the main screen).

But before I also had this issue since last update. 

Thomas

**Comment by technikamateur** [comment]
For me it's still unsolved. It works for my other network called "Lollibus". I think there is a problem with the matching algorithm. Maybe because of the spaces?

**Comment by zaneschepke** [comment]
Hello! This should be fixed in the latest version 3.6.0. With the introduction of the wildcards feature, matching was getting messed up because of regex. I have now made the use of wildcards a toggle setting so, by default, it is not enabled which will default to regular string matching. 

Let me know if this is still not fixed in 3.6.0 and we can reopen.
