### ISSUE TITLE
Issue with rooted devices

### ISSUE THREAD

**Issue by timur-g** [zaneschepke/wgtunnel#46]
I tried this from F-Droid but coud not establish a tunnel. Just "Attempting connection".

Problem is: I do not see an error - please add some. Also not clear where log is. 
Also, in the notification, after "VPN Connection Failed" in addition to "Restart Tunnel", maybe add "See Log".
Note: Wireguard Android client has log with error messages. 

WG did not ask for superuser permisison? Does it need it?
Note:  Wireguard Android client asks for superuser premission.

**Comment by zaneschepke** [comment]
Hello! Thank you for using the app. 

WG Tunnel only supports the userspace implementation of WireGuard at the moment. I am working on adding kernel support, but it is still in process. See #43. 

 I could add a feature to show logs, but I am not sure that it would be helpful in this situation. If I am not mistaken, because WireGuard uses UDP for all the communication, we won't really know why the connection is failing. There will not be an error to show except "handshake failed, trying again". WireGuard will continuously try to send handshakes to the server until it succeeds. You will see the same message in WireGuard official app logs. Unfortunately, this is not very useful for solving connection issues. 

Does this same tunnel config work in the official WireGuard app? 

Have you tried this tunnel config on an userspace implementation before?

**Comment by timur-g** [comment]
Hello, thanks for follow up. Yes, the same tunnel works in Wireguard Android. 
IDK how to "tried this tunnel config on an userspace implementation".

**Comment by timur-g** [comment]
I am on rooted phone.  I am not aware in options in official WG. I set email with sample conf. Thanks.

**Comment by zaneschepke** [comment]
I looked at your config file, and I don't see anything wrong. I do see issues happening with what I suspect to be rooted devices. I am investigating now.

**Comment by zaneschepke** [comment]
@timur-g 

I was able to root one of my devices and did not have any issues with my tunnels. 

Are you still experiencing issues with that tunnel?

What version of the app are you on? 

Something else that could be worth testing is trying the Google Play version of the app to see if it behaves differently.

**Comment by timur-g** [comment]
Somehow it started to work when I tested today, no idea why it did not work more times when I tested then (with reboot).
I am on 3.1.4 from Fdroid, I do not have Play in LineageOS.
Thanks a lot for your dedication, sorry for your time. 
Still, you may see if enhancement is possible with some logs, to avoid similar..

**Comment by zaneschepke** [comment]
I'm glad it is working! There was an issue with the previous build being deployed to F-Droid so you are on an older version. I fixed the issue so F-Droid should get the latest version soon. 

I will look into adding log viewing to the app.
