### ISSUE TITLE
[BUG] - Auto-tunelling crashing the app

### ISSUE THREAD

**Issue by zamansoum** [zaneschepke/wgtunnel#486]
**Describe the bug**
The app is constantly crashing, nothing can make me access the UI. I reinstalled and reconfigured the tunnel, everything went fine until I enabled the auto-tunneling which reproduced the issue and crashed the app forever again. This is the exact same behavior observed in  #407 

**Smartphone (please complete the following information):**

- Device: Pixel 6
- Android Version: 14
- App Version 3.6.2
- Backend: Userspace

**To Reproduce**

1.  Open the app
2.  Setup a tunnel 
3.  Whitelist an SSID, 
4.  Add permissions
5. Enable auto-tunneling 
6. See error

**Expected behavior**
Auto-tunneling to function as intended and not crash the app

**Additional context**
Other Pixel phone with 3.5.1 working fine

**Comment by zaneschepke** [comment]
Hello! Yes, there was typo when creating a notification channel that caused the wrong channel to be created and resulted in this crash when auto tunneling is started with a persistent notification. 

This has been fixed in 3.6.3, which is now live on GitHub. It should hopefully be live on Google Play soon! I'm apologize for the inconvenience. I'll wait to mark this as closed until the new version is live on Google Play.

**Comment by zaneschepke** [comment]
This is out on Play Store now. Marking this as closed.
