### ISSUE TITLE
Empty listen address can not remedy.

### ISSUE THREAD

**Issue by EvanCarroll** [zaneschepke/wgtunnel#63]
**Describe the bug**
By default, openwrt for whatever reason does not generate the listen address in the qr code, or the app itself doesn't use it when generated.

When I add the tunnel with the QR code, it has no address. This means when I try to connect it instantly fails. No problem yet.

When I try to edit the configuration though and add the listen address I can't save it. In my case the listen address I'm trying to add is `192.168.88.12/32` but when i hit save it says

> Error: empty address

Even though the address is clearly populated

**Comment by zaneschepke** [comment]
Hello! Could you please share your phone model, Android version, and app version you are using? Also, can you confirm the issue is with the interface addresses field?

**Comment by EvanCarroll** [comment]
Lineageos 18.1, OnePlus 8 Pro. Yes, the Interface Address field.

**Comment by zaneschepke** [comment]
> This is the file used to generate the qr code,
> 
> ```
> [Interface]
> PrivateKey = REDACTED=
> # ListenPort not defined
> 
> [Peer]
> PublicKey = REDACTED=
> # PresharedKey not used
> AllowedIPs = 0.0.0.0/0, ::/0
> Endpoint = 99.7.199.108:51820
> PersistentKeepAlive = 0
> ```

The problem is there is no Interface "Address" property defined. I think this is a required property. 
Example here: https://www.procustodibus.com/blog/2021/01/wireguard-endpoints-and-ip-addresses/

My config validation is not very sophisticated, so it did not detect this property is missing. This caused it to add a bad config to the app. 

I can look into adding validation to deny configs like this from being added, but the core of the issues seems to be with openwrt.

**Comment by EvanCarroll** [comment]
Why can't we just add it, and then edit it later? Your audience has to be F-droid users (especially with there not being any competition). We're the most likely people to use OpenWRT. OpenWRT is generating a reciprocal file for the router's peer. The peer on the openwrt side has multiple options for Allowed IPs. It's not clear which address you want from a potential  block allocated to the peer.

It would be highly desirable if you could fill in this information after you scanned the qr code.

**Comment by zaneschepke** [comment]
> Or take the user right to the edit screen, and force them to fill in the values. Except if they do, make the validation work.

So I think I found the problem. 

The problem is not that the "Addresses" field is missing (even though this still does need to be populated for the tunnel to work). The problem is that the DNS field on interface is also a required field. Please try to populating the DNS field on interface when you add your addresses subnet and it should all save and work as expected.

**Comment by EvanCarroll** [comment]
That doesn't make much sense even if so, what if the tunnel you're connecting to simply doesn't have or provide DNS? Mine does, but I can't see making that a required field. Certainly wg-up doesn't require it as I don't have it set on my desktop when I connect to that vpn just because I don't use DNS for it.

Also, what if the vpn provides DNS but you don't want to use it because you need to use the DNS provided by the mobile network or wifi?

**Comment by zaneschepke** [comment]
Perhaps there is something else going wrong. I should have some time to dig into this one further this week.

**Comment by EvanCarroll** [comment]
I can't populate the Address field on OpenWRT which I'm using to generate the QR code. It's not even an option =(
