### ISSUE TITLE
Feature Request: PIN code

### ISSUE THREAD

**Issue by mrbluecoat** [zaneschepke/wgtunnel#9]
Would it be possible to add the ability to set a PIN code or password that prevents settings from being changed unless entered? I.e. read-only view with admin edit rights

**Comment by zaneschepke** [comment]
Would this be a pin other than the phones pin/biometrics that the app would have to manage?

**Comment by mrbluecoat** [comment]
Yes, something only an IT admin (or parent for a child device) would know.

**Comment by zaneschepke** [comment]
Would the user still be able to turn off the Always-on VPN via Android settings? I do not want to add any pin that the app would have to manage. There is a possibility to just remove the manual setting of allowing always on VPN and let the app use it automatically. I did not go with this setup to start because I didn't want always-on VPN conflicting with the auto tunnel feature but I could just disable auto tunneling if I see always-on is being used.

**Comment by mrbluecoat** [comment]
Good points. Let's leave as-is for now.
